server:
  port: 8080

spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:9296
  
resilience4j:
  circuitbreaker:
    metrics:
      enabled: true
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 2s
        failure-rate-threshold: 5
        event-consumer-buffer-size: 10
    instances:
      PedidoCircuitBreaker:
        base-config: default
      ProductoCircuitBreaker:
        base-config: default
      UsuarioCircuitBreaker:
        base-config: default
      LoteCircuitBreaker:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 1s
        cancel-running-future: false
    instances:
      PedidoCircuitBreaker:
        base-config: default
      ProductoCircuitBreaker:
        base-config: default
      UsuarioCircuitBreaker:
        timeout-duration: 2s
      LoteCircuitBreaker:
        base-config: default